theme: jekyll-theme-slate
# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://xdhaut.xyz
date_format: "ordinal"
title: XDer
subtitle: "打码改变人生"
description: "Xder的个人博客"
keywords: Xder, XDer, xdhaut, 张建建
favicon: /favicon.ico
timezone: Asia/Xi’an
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Jian zhang
organization: Xd U
organization_url: http://www.xidian.edu.cn
github_username: Xdhauter
location: Xi'an, China
email: hautangzh@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: xdhauter/xdhauter.github.io



# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
